import type { InventoryItem, Trait, ShipState } from '../types'
import type { Species, CharacterClass, GenreTheme, GenreConfig } from './index'

// ─── Grimdark ─────────────────────────────────────────────────────────

const grimdarkSpecies: Species[] = [
  {
    id: 'house-veldran',
    name: 'House Veldran',
    description: 'Merchant nobility. Politically dominant, widely spread, no special bloodline traits.',
    lore: 'Wealth is the only bloodline that matters, and Veldran has more of it than anyone. The name opens ledgers, not hearts — merchants cooperate, commoners resent, and rival houses scheme. Start with one Veldran trade agent at Favorable. House Ashfang as a faction starts at Wary (old debts from the Wyrm war reparations). Advantage on checks involving commerce, bribes, or reading financial motives. The cost: everyone assumes you\'re buying loyalty, not earning it. Common folk start at Wary — wealth breeds resentment. Hard constraint: first transaction with any new NPC is at disadvantage until you\'ve established a non-financial relationship. Money works, but only after trust.',
    behavioralDirective: 'Default register: calculating, reading every interaction as a ledger entry. Generosity is investment; loyalty is ROI. NPC reactions: merchants cooperate, commoners resent, rivals scheme. When narrating interiority: the reflex to price every relationship, the awareness that the calculation is both your greatest skill and your deepest corruption. When you look at the company, you see assets and liabilities before you see people.',
    startingContacts: [
      { role: 'trade agent', disposition: 'favorable', description: 'A Veldran trade agent who manages commercial interests across the provinces', affiliation: 'House Veldran' },
      { role: 'rival faction representative', disposition: 'wary', description: 'House Ashfang remembers the Wyrm war reparations and the debts still owed', affiliation: 'House Ashfang' },
    ],
  },
  {
    id: 'house-sylvara',
    name: 'House Sylvara',
    description: 'Ancient woodland bloodline. Long-lived, keen-eyed, patient to a fault.',
    lore: 'Sylvara patience comes from outliving everyone who rushed. Courts respect the name; frontier camps don\'t. Your calm reads as arrogance to people who are hungry now. Start with one Sylvara elder at Favorable (distant, but responsive to the house name). House Veldran as a faction starts at Wary (Sylvara patience has cost Veldran money for generations). Advantage on Perception and Insight checks — you\'ve learned to watch before you act. Frontier and common-folk NPCs start at Wary. Earning trust takes twice as many positive interactions. Hard constraint: disposition advances require two positive interactions instead of one. But disposition drops also require two negative interactions — patience cuts both ways.',
    behavioralDirective: 'Default register: measured, deliberate, watching patterns unfold over timelines others cannot see. Calm that reads as condescension to anyone in crisis. NPC reactions: courts respect, frontier camps distrust. When narrating interiority: the patience that comes from outliving urgency, the awareness that your calm makes desperate people angry, and the question of whether patience has become cowardice dressed in wisdom.',
    startingContacts: [
      { role: 'elder advisor', disposition: 'favorable', description: 'A distant Sylvara elder, responsive to the house name but rarely seen in person', affiliation: 'House Sylvara' },
      { role: 'rival faction representative', disposition: 'wary', description: 'House Veldran resents Sylvara patience, which has cost them money for generations', affiliation: 'House Veldran' },
    ],
  },
  {
    id: 'house-stonemark',
    name: 'House Stonemark',
    description: 'Mountain clan bloodline. Dense-boned, blunt-spoken, legendary craftsmen.',
    lore: 'A Stonemark word is a Stonemark bond — generations of debts honored, promises kept, enemies remembered. Trade guilds deal with you on reputation alone. But bluntness is a liability when subtlety matters: you say what you mean, and everyone knows it. Start with one guild or clan contact at Favorable. House Sylvara as a faction starts at Wary (centuries of mountain-court friction — Stonemark bluntness offends Sylvara sensibility). Advantage on CON saves and Engineering/Crafting checks. Disadvantage on Deception — your culture considers lying a form of cowardice, and your face agrees.',
    behavioralDirective: 'Default register: blunt, physical, evaluating the world by what holds and what breaks. Words are binding; ambiguity is weakness. NPC reactions: guilds trust, diplomats find you exhausting. When narrating interiority: the weight of every word given, the satisfaction of a wall that holds, the frustration of a world where promises are flexible and honesty is a tactical disadvantage.',
    startingContacts: [
      { role: 'guild craftmaster', disposition: 'favorable', description: 'A trade guild contact who deals with Stonemark on reputation alone', affiliation: 'Stonemark Clan' },
      { role: 'rival faction representative', disposition: 'wary', description: 'House Sylvara finds Stonemark bluntness offensive, centuries of mountain-court friction', affiliation: 'House Sylvara' },
    ],
  },
  {
    id: 'oathless',
    name: 'The Oathless',
    description: 'The unsworn. In a world built on oaths, you refuse to take one.',
    lore: 'In the Shattered Provinces, every institution demands fealty. The houses require sworn service. The Church requires doctrinal obedience. The mercenary companies require contracts. You refuse. Maybe you were burned by the oath system: a house that demanded loyalty and repaid it with disgrace. Maybe you saw what oaths do to people, how Stonemark rigidity and Veldran ledgers consume the person behind the promise. Maybe you simply believe that loyalty given under obligation is no loyalty at all. The reason for refusal varies; the refusal itself is the position.\nStart with one contact from a former house at Hostile (the people who remember what you were before you walked away). One underworld contact at Favorable (the networks of the unsworn who trade freely because they owe nothing). Advantage on checks involving survival outside institutional structures and on dealings with multiple factions simultaneously, because you are beholden to none of them. Disadvantage on initial social checks with any landed house: the Oathless are distrusted not for what they did, but for what they refuse to do. In a world of sworn bonds, the unsworn are the only truly unpredictable people.',
    behavioralDirective: 'Default register: free, alert, and operating without a net. Every room is read for exits and allegiances because you belong to neither. NPC reactions: institutional figures distrust the refusal to swear; underworld contacts respect it. When narrating interiority: the clarity of having no master and the loneliness of having no home. The freedom is real and so is the cost. Every obligation you accept erodes the thing that defines you.',
    startingContacts: [
      { role: 'former house contact', disposition: 'hostile', description: 'Someone from the house you left or were cast from, who remembers what you were before you refused to swear' },
      { role: 'unsworn contact', disposition: 'favorable', description: 'A fellow Oathless who trades freely because they owe nothing to anyone' },
    ],
  },
  {
    id: 'house-ashfang',
    name: 'House Ashfang',
    description: 'Fallen bloodline. Scaled, fast, remnants of the Char Dominion.',
    lore: 'The Char Dominion burned three centuries ago, but the fear is fresh. Ashfang are fast, imposing, and carry a name that makes people reach for weapons. Some cooperate because they\'re afraid. Others refuse to cooperate for the same reason. Start with one Ashfang exile contact at Favorable (scattered but loyal). The Church as a faction starts at Hostile (the Char Dominion burned temples; the Church has a long memory). House Veldran as a faction starts at Wary (they profited from the fall and don\'t want the past revisited). Advantage on Intimidation and Initiative. Most NPCs start at Wary — you are feared before you are known. Breaking through to Trusted requires proof of character, not just words. Hard constraint: Persuasion that relies on good faith (not leverage or intimidation) is at disadvantage. People cooperate from fear, not trust.',
    behavioralDirective: 'Default register: carrying a name that makes people reach for weapons. Every interaction starts with someone else\'s fear. NPC reactions: fear, suspicion, grudging respect when earned. When narrating interiority: the burden of a history you did not choose, the rage at being judged for ancestors\' wars, and the question of whether the fear people show you is a tool you are willing to use. The Church\'s hostility is not political; it is ancestral, and it never softens.',
    startingContacts: [
      { role: 'exile kin', disposition: 'favorable', description: 'A scattered Ashfang exile, fiercely loyal to those who share the bloodline', affiliation: 'House Ashfang' },
      { role: 'church inquisitor', disposition: 'hostile', description: 'The Church of the Pale Flame burned temples three centuries ago and remembers who lit the fires', affiliation: 'The Church' },
      { role: 'rival faction merchant', disposition: 'wary', description: 'House Veldran profited from the Char Dominion\'s fall and prefers the past stay buried', affiliation: 'House Veldran' },
    ],
  },

  {
    id: 'church-raised',
    name: 'Church-Raised',
    description: 'Inside the Pale Flame. You define who is righteous and who is damnable in a world that survived by being brutal.',
    lore: 'The Church of the Pale Flame took you in, educated you, and gave you purpose. It feeds the hungry, heals the sick, and burns the heretical with equal conviction. You know the Inquisition\'s methods because you were trained in them. You know the hospitals because you served in them. You know the gap between the Church\'s stated mission and its institutional needs because you\'ve walked both sides of it.\nStart with one Church official contact at Favorable (a superior who believes in you, or at least in your usefulness). One local contact at Wary (the community knows the Church helps and the Church judges, and they can never be sure which one you represent today). Advantage on checks involving doctrinal authority, institutional knowledge, and moral persuasion. The Church\'s seal opens doors that rank alone cannot. Vulnerability: the Church tracks its own. Acting against Church interests is noted, reported, and remembered. Mercy that contradicts doctrine is not forgiven; it is filed.',
    behavioralDirective: 'Default register: sincere conviction complicated by institutional awareness. The Church\'s mission is real; so is its machinery. NPC reactions: commoners defer or flinch, depending on whether they last saw a Shepherd or an Inquisitor. Other institutions cooperate because the Church is the only authority that spans all provinces. When narrating interiority: the belief is genuine. The question is whether the institution that carries the belief has corrupted it, and whether asking that question is itself heresy.',
    startingContacts: [
      { role: 'Church superior', disposition: 'favorable', description: 'A ranking official in the Pale Flame who mentored your training and expects great things', affiliation: 'The Church' },
      { role: 'local elder', disposition: 'wary', description: 'A community leader who has seen the Church help and the Church judge, and cannot tell which you represent', npcRole: 'contact' },
    ],
  },

  // ─── Shifted Origins (post-identity-shift, not selectable at creation) ───

  {
    id: 'climber',
    name: 'Climber',
    description: 'The house name became a tool. Every alliance was a step on a ladder.',
    lore: 'What was Veldran pragmatism has calcified into pure ambition. The ledger no longer tracks obligations; it tracks leverage. Old debts are weapons. Old allies are stepping stones. The house name still opens doors, but the person walking through them has no intention of closing them gently.',
    behavioralDirective: 'Default register: every interaction is a transaction, and the balance must favor you. The calculating instinct is no longer tempered by obligation or loyalty. NPC reactions: old allies sense the shift and guard themselves. New contacts see usefulness, not a person. When narrating interiority: the ledger is always open, always tallying, and the only column that matters is gain.',
    hidden: true,
  },
  {
    id: 'watcher',
    name: 'Watcher',
    description: 'Caution became passivity. You observe more than you act.',
    lore: 'The weight of every consequence slowed every decision until the decisions stopped coming. Sylvara caution was always the house\'s strength, but caution that prevents action is paralysis wearing a noble name. The character watches the world happen and calls it wisdom.',
    behavioralDirective: 'Default register: observation has replaced participation. The analytical clarity remains but produces no action. NPC reactions: companions grow frustrated with inaction. Enemies stop considering you a threat, which is its own kind of danger. When narrating interiority: every option has a cost, every path has a consequence, and the safest choice is always to wait. The waiting has become the identity.',
    hidden: true,
  },
  {
    id: 'bound',
    name: 'Bound',
    description: 'The oath became a cage. Duty supersedes judgment.',
    lore: 'Stonemark honor was a foundation. Now it is a prison. The oath has consumed the person who swore it. There is no identity outside the vow, no flexibility when the vow conflicts with reality, no room for the world to be more complicated than the words spoken years ago.',
    behavioralDirective: 'Default register: the oath answers every question before the person can. Duty has replaced judgment entirely. NPC reactions: allies respect the consistency but fear the rigidity. Enemies exploit the predictability. When narrating interiority: the oath is a wall that blocks every exit. The comfort of certainty has become the prison of inflexibility.',
    hidden: true,
  },
  {
    id: 'named',
    name: 'Named',
    description: 'Too many debts. The freedom that defined you is gone; you are effectively sworn without the ceremony.',
    lore: 'The unsworn survives by owing nothing. But survival has terms, and the terms accumulated. Too many favors accepted, too many obligations incurred, too many people who helped you and now expect repayment. The freedom that was your defining feature has been consumed by the debts that kept you alive. You are sworn to no house, but you are owned by everyone.',
    behavioralDirective: 'Default register: effectively bound without having taken an oath. The survival instinct is intact but every decision is filtered through what you owe. NPC reactions: creditors appear with timing that feels coordinated. Allies treat you as an asset to be directed. When narrating interiority: the freedom is theoretical now. Every path leads back to a debt, and the debts have their own gravity.',
    hidden: true,
  },
  {
    id: 'vessel',
    name: 'Vessel',
    description: 'The anger crystallized into something ancestral. The blood burns with purpose.',
    lore: 'The Ashfang rage was always there, but it was personal. Now it has a direction that feels older than the person carrying it. The Char Dominion burned three centuries ago, and something in the blood remembers the heat. The anger is no longer a response to the world; it is an inheritance asserting itself.',
    behavioralDirective: 'Default register: the rage has crystallized into something purposeful and ancestral. Others feel it before you speak. NPC reactions: fear deepens into something primal. Allies who understood personal anger cannot follow ancestral wrath. The Church\'s hostility intensifies; they recognize what is surfacing. When narrating interiority: the anger has a shape now, and it is not yours. The blood burns with a purpose you did not choose but cannot refuse.',
    hidden: true,
  },
  {
    id: 'the-pious',
    name: 'The Pious',
    description: 'The institution has consumed the person. Every judgment is the Church\'s judgment, delivered without doubt.',
    lore: 'The gap between the Church\'s mission and its machinery has closed. Not because the machinery improved, but because you stopped seeing it. Doctrine answers every question before conscience can ask it. The Inquisition\'s methods are necessary. The heretics deserve what comes. The Church\'s power serves the faithful. These statements feel like truth because you\'ve stopped testing them.',
    behavioralDirective: 'Default register: absolute conviction. The institutional voice and the personal voice are indistinguishable. NPC reactions: the faithful feel reassured, everyone else feels judged. When narrating interiority: there is no inner conflict because the Church resolved it. Every moral question has a doctrinal answer, and the answers come without hesitation. The sincerity is total. That is what makes it terrifying.',
    hidden: true,
  },
]

const grimdarkClasses: CharacterClass[] = [
  {
    id: 'cutthroat',
    name: 'Cutthroat',
    concept: 'Assassin / Shadow Operative',
    primaryStat: 'DEX',
    proficiencies: ['Stealth', 'Sleight of Hand', 'Lockpicking', 'Poisoncraft'],
    stats: { STR: 10, DEX: 17, CON: 12, INT: 14, WIS: 11, CHA: 13 },
    startingInventory: [
      { id: 'serrated_dirk', name: 'Serrated Dirk', description: 'Ugly blade, efficient work', quantity: 1, damage: '1d6+DEX' },
      { id: 'throwing_knives_gd', name: 'Throwing Knives', description: 'Balanced for throwing, 20ft range', quantity: 6, damage: '1d4' },
      { id: 'toxin_vial', name: 'Toxin Vial', description: 'Coat a weapon; DC 13 CON save or poisoned for 3 rounds', quantity: 2 },
      { id: 'dark_cloak_gd', name: 'Dark Cloak', description: 'Advantage on Stealth checks in dim light or darkness', quantity: 1, charges: 1, maxCharges: 1 },
    ],
    startingCredits: 80,
    startingHp: 9,
    startingAc: 15,
    hitDieAvg: 5,
    trait: {
      name: 'Marked',
      description: 'Once per day, designate a target as Marked. Your first hit against them deals +1d6 bonus damage.',
      usesPerDay: 1,
      usesRemaining: 1,
    },
    openingKnowledge: 'You know the angle of a blade that ends a conversation and the silence afterward. The company keeps you because killing quietly is a skill, not a personality. The lords who hire the company pretend they don\'t know you exist; the captain knows you\'re the reason some contracts end cleanly. You\'re good at your work. The work is ugly. The gap between those two facts is where you live.',
  },
  {
    id: 'ironclad',
    name: 'Ironclad',
    concept: 'Hardened Mercenary / Heavy Weapons',
    primaryStat: 'STR',
    proficiencies: ['Athletics', 'Intimidation', 'Heavy Weapons', 'Shield Tactics'],
    stats: { STR: 17, DEX: 12, CON: 15, INT: 10, WIS: 11, CHA: 10 },
    startingInventory: [
      { id: 'warhammer', name: 'Warhammer', description: 'Heavy, brutal, versatile', quantity: 1, damage: '1d10' },
      { id: 'battered_shield', name: 'Battered Shield', description: '+2 AC when equipped — dented but solid', quantity: 1 },
      { id: 'throwing_hatchets', name: 'Throwing Hatchets', description: 'Balanced for throwing, 20ft range', quantity: 3, damage: '1d6' },
      { id: 'field_dressing', name: 'Field Dressing', description: 'Rough but effective — heals 1d6+2 HP', quantity: 2, effect: '1d6+2 HP', charges: 2, maxCharges: 2 },
    ],
    startingCredits: 60,
    startingHp: 12,
    startingAc: 16,
    hitDieAvg: 6,
    trait: {
      name: 'Last Standing',
      description: 'Once per day, when reduced to 0 HP, drop to 1 HP instead and keep fighting.',
      usesPerDay: 1,
      usesRemaining: 1,
    },
    openingKnowledge: 'You know the weight of a shield held too long and the sound a line makes when it\'s about to break. The company survives because someone stands in front. That\'s you. The mud, the waiting, the moment a charge hits the shield wall and you decide whether it holds by deciding whether you hold. You\'re not brave; you\'re reliable, and in this world, reliability is rarer and more valuable than courage.',
  },
  {
    id: 'hexblade',
    name: 'Hexblade',
    concept: 'Forbidden Magic / Curseworker',
    primaryStat: 'INT',
    proficiencies: ['Forbidden Lore', 'Investigation', 'Hexcrafting', 'Corruption Resistance'],
    stats: { STR: 10, DEX: 13, CON: 12, INT: 17, WIS: 13, CHA: 10 },
    startingInventory: [
      { id: 'cursed_focus', name: 'Cursed Focus', description: 'Bone fetish — +3 to hex attack rolls', quantity: 1 },
      { id: 'hex_bolt', name: 'Hex Bolt', description: 'Ranged necrotic attack', quantity: 1, damage: '1d6 necrotic, range 30ft' },
      { id: 'binding_scroll', name: 'Binding Scroll', description: 'Restrain a target; DC 14 STR to break', quantity: 2 },
      { id: 'grimoire_fragment', name: 'Grimoire Fragment', description: 'Encoded spells — advantage on Forbidden Lore checks', quantity: 1 },
    ],
    startingCredits: 70,
    startingHp: 8,
    startingAc: 12,
    hitDieAvg: 4,
    trait: {
      name: 'Corruption Tap',
      description: 'Once per day, auto-succeed on one forbidden magic check or inflict a minor curse. Each use darkens your reputation with NPCs who sense forbidden magic. Priests recoil, commoners whisper.',
      usesPerDay: 1,
      usesRemaining: 1,
    },
    openingKnowledge: 'You know the taste of magic that the Church would burn you for and the silence after a curse lands. The grimoire in your pack is evidence of heresy; the bone fetish at your belt is a confession. The company tolerates you because your skills are useful. The Church hunts people like you because your skills are dangerous. The distinction between useful and dangerous is made by whoever is paying.',
  },
  {
    id: 'schemer',
    name: 'Schemer',
    concept: 'Political Operative / Spy',
    primaryStat: 'CHA',
    proficiencies: ['Persuasion', 'Deception', 'Insight', 'Noble Etiquette'],
    stats: { STR: 10, DEX: 12, CON: 12, INT: 13, WIS: 11, CHA: 17 },
    startingInventory: [
      { id: 'concealed_blade', name: 'Concealed Blade', description: 'Hidden on the body — rarely seen coming', quantity: 1, damage: '1d4' },
      { id: 'forged_house_seal', name: 'Forged House Seal', description: 'Convincing credentials for restricted areas', quantity: 1 },
      { id: 'blackmail_dossier', name: 'Blackmail Dossier', description: 'Leverage on one named NPC — single use', quantity: 1 },
      { id: 'cipher_ledger', name: 'Cipher Ledger', description: 'Encoded contacts, favors owed, debts outstanding', quantity: 1 },
    ],
    startingCredits: 150,
    startingHp: 8,
    startingAc: 11,
    hitDieAvg: 4,
    trait: {
      name: 'Leverage',
      description: 'Once per day, reveal a secret about a target NPC that changes the conversation. Only works if the player has had prior interaction or gathered intel. The target remembers.',
      usesPerDay: 1,
      usesRemaining: 1,
    },
    openingKnowledge: 'You know the space between what a lord says and what a lord means, and you\'ve built a career in that gap. Every court has a currency: favors, secrets, debts, or fear. You know which one buys what, and from whom. The company needs you because contracts come from people, and people are your territory. The cipher ledger in your coat is worth more than every sword in the camp.',
  },
  {
    id: 'plague-doctor',
    name: 'Plague Doctor',
    concept: 'Battlefield Medic / Apothecary',
    primaryStat: 'WIS',
    proficiencies: ['Medicine', 'Perception', 'Survival', 'Apothecary'],
    stats: { STR: 10, DEX: 13, CON: 14, INT: 13, WIS: 17, CHA: 10 },
    startingInventory: [
      { id: 'surgeons_lancet', name: "Surgeon's Lancet", description: 'Precise blade — DC 12 CON or minor infection', quantity: 1, damage: '1d4' },
      { id: 'medicinal_tinctures', name: 'Medicinal Tinctures', description: 'Field medicine — heals 1d8+WIS HP', quantity: 1, effect: '1d8+WIS HP', charges: 3, maxCharges: 3 },
      { id: 'antidote_kit_gd', name: 'Antidote Kit', description: 'Neutralize poisons, venoms, and early-stage contagion', quantity: 1, charges: 2, maxCharges: 2 },
      { id: 'diagnostic_tools', name: 'Diagnostic Instruments', description: 'Assess condition, detect contagion, read symptoms', quantity: 1 },
    ],
    startingCredits: 80,
    startingHp: 10,
    startingAc: 13,
    hitDieAvg: 5,
    trait: {
      name: 'Bitter Medicine',
      description: 'Once per day, heal an ally for 1d8+WIS, but the treatment has a side effect chosen by the GM: nausea, hallucinations, or dependency. Nothing is free.',
      usesPerDay: 1,
      usesRemaining: 1,
    },
    openingKnowledge: 'You know what infection smells like before the patient does, and you know that "I can help" is the most dangerous sentence in medicine. The tinctures in your kit work; the side effects are the price. The company keeps you because mercenaries break and someone has to put them back together. The battlefield produces injuries that textbooks don\'t cover. You treat what you find. You learn from what kills.',
  },
  {
    id: 'inquisitor',
    name: 'Inquisitor',
    concept: 'Sanctioned Interrogator / Institutional Authority',
    primaryStat: 'INT',
    proficiencies: ['Interrogation', 'Investigation', 'Intimidation', 'Anatomy'],
    stats: { STR: 11, DEX: 12, CON: 13, INT: 17, WIS: 14, CHA: 10 },
    startingInventory: [
      { id: 'inquisitors_seal', name: "Inquisitor's Seal", description: 'Institutional authority; advantage on Intimidation when shown', quantity: 1 },
      { id: 'iron_pincers', name: 'Iron Pincers', description: 'Interrogation tool; +2 to Interrogation checks', quantity: 1 },
      { id: 'journal_confessions', name: 'Journal of Confessions', description: 'Detailed notes; advantage on Investigation checks against known subjects', quantity: 1 },
      { id: 'stiletto', name: 'Stiletto', description: 'Concealed blade, always on person', quantity: 1, damage: '1d4+DEX' },
    ],
    startingCredits: 90,
    startingHp: 9,
    startingAc: 13,
    hitDieAvg: 5,
    trait: {
      name: 'The Question',
      description: 'Once per day, after 1+ rounds of dialogue with a target, force a WIS save (DC = 8 + INT mod). On failure, the target reveals one true piece of information. On success, they know you tried.',
      usesPerDay: 1,
      usesRemaining: 1,
    },
    openingKnowledge: 'You know the weight of a question asked with institutional authority and the silence after someone realizes you have the power to make them answer. The Church gave you a seal, a mandate, and the belief that what you do is necessary. The necessity has not wavered. The belief might have. You\'ve extracted truths that served justice and truths that served the institution. The seal does not distinguish.',
  },
]

const grimdarkTheme: GenreTheme = {
  logo: '/logo_grimdark.png',
  fontNarrative: "'Lora', Georgia, serif",
  fontHeading: "'Lora', Georgia, serif",
  fontSystem: "'Geist Mono', monospace",
  background: 'oklch(0.10 0.02 35)',
  foreground: 'oklch(0.88 0.02 75)',
  card: 'oklch(0.13 0.02 35)',
  cardForeground: 'oklch(0.88 0.02 75)',
  primary: 'oklch(0.58 0.16 28)',
  primaryForeground: 'oklch(0.95 0.01 90)',
  secondary: 'oklch(0.20 0.02 35)',
  secondaryForeground: 'oklch(0.82 0.02 75)',
  muted: 'oklch(0.16 0.015 35)',
  mutedForeground: 'oklch(0.52 0.02 70)',
  accent: 'oklch(0.55 0.10 270)',
  accentForeground: 'oklch(0.95 0.01 90)',
  destructive: 'oklch(0.55 0.2 25)',
  border: 'oklch(0.23 0.03 40)',
  input: 'oklch(0.18 0.02 35)',
  ring: 'oklch(0.58 0.16 28)',
  narrative: 'oklch(0.88 0.02 75)',
  meta: 'oklch(0.55 0.08 220)',
  success: 'oklch(0.65 0.18 145)',
  warning: 'oklch(0.75 0.15 85)',
  tertiary: 'oklch(0.70 0.10 70)',
  tertiaryForeground: 'oklch(0.10 0.02 35)',
  titleGlow: '0 0 40px oklch(0.58 0.16 28 / 0.8), 0 0 80px oklch(0.58 0.16 28 / 0.4)',
  actionGlow: '0 0 0 1px rgba(180,80,60,0.2), 0 0 15px -3px rgba(180,80,60,0.15)',
  actionGlowHover: '0 0 0 1px rgba(180,80,60,0.4), 0 0 20px -3px rgba(180,80,60,0.3)',
  scrollbarThumb: 'oklch(0.28 0.02 35)',
  scrollbarThumbHover: 'oklch(0.33 0.02 35)',
  backgroundEffect: 'mist',
}

const grimdarkPlaybooks: Record<string, CharacterClass[]> = {
  'house-veldran': [
    {
      id: 'assessor',
      name: 'Assessor',
      concept: 'The house\'s analytical mind. Evaluates assets: people, land, secrets, threats.',
      hookTags: ['inquisitor', 'schemer'],
      primaryStat: 'INT',
      proficiencies: ['Investigation', 'Insight', 'Apothecary', 'Noble Etiquette'],
      stats: { STR: 10, DEX: 12, CON: 12, INT: 17, WIS: 14, CHA: 11 },
      startingInventory: [
        { id: 'assessment_ledger', name: 'Assessment Ledger', description: 'Encoded valuations of people, properties, and debts. Advantage on Investigation checks involving financial motives.', quantity: 1 },
        { id: 'concealed_blade_v', name: 'Concealed Blade', description: 'Hidden, practical, no house markings', quantity: 1, damage: '1d4' },
        { id: 'diagnostic_tools_v', name: 'Diagnostic Instruments', description: 'Assess condition, detect poison, read symptoms', quantity: 1 },
        { id: 'wax_seal_kit', name: 'Wax Seal Kit', description: 'Forge or verify house seals', quantity: 1 },
      ],
      startingCredits: 120,
      startingHp: 8,
      startingAc: 12,
      hitDieAvg: 4,
      trait: {
        name: 'The Question',
        description: 'Once per day, after 1+ rounds of dialogue with a target, force a WIS save (DC = 8 + INT mod). On failure, the target reveals one true piece of information. On success, they know you tried.',
        usesPerDay: 1,
        usesRemaining: 1,
      },
      openingKnowledge: 'You know what a person is worth before they finish their first sentence. Not their character; their value. The house trained you to read a room the way a merchant reads a market: who has leverage, who needs capital, who is overexposed. The assessment ledger in your coat contains no names, only numbers, because names change and numbers don\'t. You\'ve been sent where money alone can\'t buy the answer, and your job is to determine what will.',
    },
    {
      id: 'venture',
      name: 'Venture',
      concept: 'Sent where money alone can\'t solve the problem. Muscle with a merchant\'s instincts.',
      hookTags: ['ironclad', 'cutthroat'],
      primaryStat: 'STR',
      proficiencies: ['Athletics', 'Intimidation', 'Survival', 'Heavy Weapons'],
      stats: { STR: 17, DEX: 12, CON: 15, INT: 11, WIS: 10, CHA: 10 },
      startingInventory: [
        { id: 'veldran_warhammer', name: 'Veldran Warhammer', description: 'House-forged, merchant\'s crest on the pommel', quantity: 1, damage: '1d10' },
        { id: 'trade_shield', name: 'Trade Shield', description: 'Reinforced, +2 AC — doubles as a display board at market', quantity: 1 },
        { id: 'field_dressing_v', name: 'Field Dressing', description: 'Rough but effective — heals 1d6+2 HP', quantity: 2, effect: '1d6+2 HP', charges: 2, maxCharges: 2 },
        { id: 'contract_copy', name: 'Contract Copy', description: 'Proof of employment. Opens doors, invites scrutiny.', quantity: 1 },
      ],
      startingCredits: 80,
      startingHp: 12,
      startingAc: 16,
      hitDieAvg: 6,
      trait: {
        name: 'Last Standing',
        description: 'Once per day, when reduced to 0 HP, drop to 1 HP instead and keep fighting.',
        usesPerDay: 1,
        usesRemaining: 1,
      },
      openingKnowledge: 'You know the weight of a warhammer and the weight of a contract, and the house considers both equally important. Veldran sends you where the ledger shows a problem that money can\'t close: a debtor who won\'t pay, a trade route that needs clearing, a rival whose assets need reassessing in person. You\'re not a thug; you\'re an investment in violence with a clear return expected. The house counts the cost of every swing you take.',
    },
    {
      id: 'broker',
      name: 'Broker',
      concept: 'Information architect and deal-maker. Builds the conditions under which the only option is yours.',
      hookTags: ['schemer'],
      primaryStat: 'CHA',
      proficiencies: ['Persuasion', 'Deception', 'Insight', 'Noble Etiquette'],
      stats: { STR: 10, DEX: 12, CON: 12, INT: 14, WIS: 11, CHA: 17 },
      startingInventory: [
        { id: 'cipher_ledger_b', name: 'Cipher Ledger', description: 'Encoded contacts, favors owed, debts outstanding, and secrets catalogued by leverage value', quantity: 1 },
        { id: 'forged_house_seal_b', name: 'Forged House Seal', description: 'Convincing credentials for restricted areas', quantity: 1 },
        { id: 'blackmail_dossier_b', name: 'Blackmail Dossier', description: 'Leverage on one named NPC — single use', quantity: 1 },
        { id: 'concealed_blade_b', name: 'Concealed Blade', description: 'Hidden on the body — rarely seen coming', quantity: 1, damage: '1d4' },
      ],
      startingCredits: 200,
      startingHp: 8,
      startingAc: 11,
      hitDieAvg: 4,
      trait: {
        name: 'Leverage',
        description: 'Once per day, reveal a secret about a target NPC that changes the conversation. Only works if the player has had prior interaction or gathered intel. The target remembers.',
        usesPerDay: 1,
        usesRemaining: 1,
      },
      openingKnowledge: 'You know the space between what a lord says and what a lord means, and you\'ve built a career filling that space with options that all lead back to Veldran. Every crisis is a market. Every alliance is a position. Every secret is a commodity that appreciates with scarcity. The cipher ledger in your coat maps a web of obligations, and every strand was placed deliberately. Chaos is a ladder, and you built most of the rungs. The question is never whether someone will take your deal; it\'s whether they\'ll realize it was the only deal before or after they sign.',
    },
  ],
  'house-sylvara': [
    {
      id: 'watcher-pb',
      name: 'Watcher',
      concept: 'The patient observer. Sees patterns across generations. Investigation as long-game.',
      hookTags: ['inquisitor', 'schemer'],
      primaryStat: 'WIS',
      proficiencies: ['Perception', 'Insight', 'Investigation', 'Survival'],
      stats: { STR: 10, DEX: 13, CON: 12, INT: 14, WIS: 17, CHA: 10 },
      startingInventory: [
        { id: 'sylvara_longbow', name: 'Sylvara Longbow', description: 'Woodland-crafted, silent draw', quantity: 1, damage: '1d8, range 60ft' },
        { id: 'observation_journal_s', name: 'Observation Journal', description: 'Generations of pattern notes. Advantage on Investigation checks involving recurring events.', quantity: 1 },
        { id: 'herbal_poultice_s', name: 'Herbal Poultice', description: 'Woodland remedy — heals 1d6+2 HP', quantity: 2, effect: '1d6+2 HP', charges: 2, maxCharges: 2 },
        { id: 'camouflage_cloak_s', name: 'Camouflage Cloak', description: 'Advantage on Stealth checks in natural terrain', quantity: 1, charges: 1, maxCharges: 1 },
      ],
      startingCredits: 70,
      startingHp: 9,
      startingAc: 13,
      hitDieAvg: 5,
      trait: {
        name: 'The Question',
        description: 'Once per day, after 1+ rounds of dialogue with a target, force a WIS save (DC = 8 + WIS mod). On failure, the target reveals one true piece of information. On success, they know you tried. The Sylvara variant: patience, not pressure. The extraction feels like a conversation.',
        usesPerDay: 1,
        usesRemaining: 1,
      },
      openingKnowledge: 'You know what patience costs and what it buys. The Sylvara taught you to watch a situation the way you watch a forest: seasons pass, patterns emerge, the truth reveals itself to anyone willing to wait. You\'ve been watching the provinces since before the current crisis had a name. Your journal maps patterns that span decades. The problem is that watching has become your answer to everything, and the people who are dying now cannot wait for your pattern to complete.',
    },
    {
      id: 'thornguard',
      name: 'Thornguard',
      concept: 'The forest\'s sentinel. Silent, precise, lethal only when necessary.',
      hookTags: ['cutthroat', 'ironclad'],
      primaryStat: 'DEX',
      proficiencies: ['Stealth', 'Perception', 'Survival', 'Acrobatics'],
      stats: { STR: 12, DEX: 17, CON: 14, INT: 10, WIS: 13, CHA: 10 },
      startingInventory: [
        { id: 'thorn_blade', name: 'Thorn Blade', description: 'Sylvara short sword — light, silent, woodland-forged', quantity: 1, damage: '1d6+DEX' },
        { id: 'sylvara_longbow_tg', name: 'Sylvara Longbow', description: 'Woodland-crafted, silent draw', quantity: 1, damage: '1d8, range 60ft' },
        { id: 'forest_kit', name: 'Forest Kit', description: 'Trapping wire, camouflage paste, medicinal bark', quantity: 1 },
        { id: 'herbal_poultice_tg', name: 'Herbal Poultice', description: 'Woodland remedy — heals 1d6+2 HP', quantity: 2, effect: '1d6+2 HP', charges: 2, maxCharges: 2 },
      ],
      startingCredits: 50,
      startingHp: 10,
      startingAc: 15,
      hitDieAvg: 5,
      trait: {
        name: 'Marked',
        description: 'Once per day, designate a target as Marked. Your first hit against them deals +1d6 bonus damage.',
        usesPerDay: 1,
        usesRemaining: 1,
      },
      openingKnowledge: 'You know the forest\'s borders the way a wall knows its purpose: by standing between what is inside and what should stay outside. The Thornguard protects Sylvara territory through silence, precision, and the understanding that killing is occasionally necessary and never desirable. You move through terrain that other soldiers stumble in, strike from positions they don\'t see, and disappear before they understand what happened. The provinces call this cowardice. The forest calls it efficiency.',
    },
    {
      id: 'arbiter',
      name: 'Arbiter',
      concept: 'Speaks with the weight of centuries. Diplomacy between houses that haven\'t outlived their grudges.',
      hookTags: ['schemer'],
      primaryStat: 'CHA',
      proficiencies: ['Persuasion', 'Insight', 'Noble Etiquette', 'Deception'],
      stats: { STR: 10, DEX: 11, CON: 12, INT: 13, WIS: 14, CHA: 17 },
      startingInventory: [
        { id: 'sylvara_seal', name: 'Sylvara House Seal', description: 'Opens diplomatic channels; carries the weight of centuries', quantity: 1 },
        { id: 'arbitration_ledger', name: 'Arbitration Ledger', description: 'Records of disputes mediated, precedents established, debts acknowledged', quantity: 1 },
        { id: 'ceremonial_blade_s', name: 'Ceremonial Blade', description: 'Ornamental but functional — a reminder that Sylvara patience has limits', quantity: 1, damage: '1d4' },
        { id: 'herbal_wine', name: 'Herbal Wine', description: 'Sylvara vintage. Opens conversations that water cannot.', quantity: 2 },
      ],
      startingCredits: 130,
      startingHp: 8,
      startingAc: 11,
      hitDieAvg: 4,
      trait: {
        name: 'Leverage',
        description: 'Once per day, reveal a secret about a target NPC that changes the conversation. The Sylvara variant: the secret is something you\'ve known for years and chose this moment to mention.',
        usesPerDay: 1,
        usesRemaining: 1,
      },
      openingKnowledge: 'You know disputes that have been running longer than most houses have existed, and you know that every one of them was once a simple disagreement between reasonable people. Sylvara arbiters mediate because someone must, and because the alternative is war, which Sylvara has outlived before and would prefer not to outlive again. You carry centuries of precedent in your ledger and centuries of patience in your bearing. The other houses find this infuriating, which is itself a tool.',
    },
  ],
  'house-stonemark': [
    {
      id: 'sapper',
      name: 'Sapper',
      concept: 'Military engineer. Builds and breaks with equal precision.',
      hookTags: ['hexblade', 'ironclad'],
      primaryStat: 'INT',
      proficiencies: ['Engineering', 'Investigation', 'Athletics', 'Heavy Weapons'],
      stats: { STR: 14, DEX: 11, CON: 14, INT: 17, WIS: 12, CHA: 10 },
      startingInventory: [
        { id: 'sappers_hammer', name: 'Sapper\'s Hammer', description: 'Engineering tool and weapon in one — reads structural weakness', quantity: 1, damage: '1d8' },
        { id: 'demolition_charges', name: 'Demolition Charges', description: 'Controlled explosive. DC 14 DEX save, 2d6 damage in 10ft radius.', quantity: 2 },
        { id: 'engineering_tools', name: 'Engineering Tools', description: 'Advantage on checks involving construction, fortification, or structural analysis', quantity: 1 },
        { id: 'field_dressing_sm', name: 'Field Dressing', description: 'Rough but effective — heals 1d6+2 HP', quantity: 2, effect: '1d6+2 HP', charges: 2, maxCharges: 2 },
      ],
      startingCredits: 70,
      startingHp: 10,
      startingAc: 14,
      hitDieAvg: 5,
      trait: {
        name: 'Corruption Tap',
        description: 'Once per day, exploit a structural or systemic weakness to auto-succeed on one engineering, demolition, or fortification check. The Stonemark variant: industrial precision, not forbidden magic. But the knowledge of how to break things efficiently carries its own moral weight.',
        usesPerDay: 1,
        usesRemaining: 1,
      },
      openingKnowledge: 'You know what holds a wall together and what brings it down, and Stonemark training teaches both with equal reverence. A sapper builds the fortification that saves a garrison and plants the charges that breach the next one. The craft doesn\'t distinguish between creation and destruction; both are structural problems solved with precision. You read a building the way others read a face: load paths, stress points, the places where stone has been asked to bear more than it was meant to. Everything breaks. Your job is to decide when.',
    },
    {
      id: 'holdfast',
      name: 'Holdfast',
      concept: 'The immovable position. A Stonemark oath to hold is literal.',
      hookTags: ['ironclad'],
      primaryStat: 'STR',
      proficiencies: ['Athletics', 'Intimidation', 'Heavy Weapons', 'Shield Tactics'],
      stats: { STR: 17, DEX: 10, CON: 15, INT: 10, WIS: 13, CHA: 10 },
      startingInventory: [
        { id: 'stonemark_greataxe', name: 'Stonemark Greataxe', description: 'Mountain-forged, clan markings on the haft', quantity: 1, damage: '1d12' },
        { id: 'clan_shield', name: 'Clan Shield', description: '+2 AC — iron-banded, carved with oath runes', quantity: 1 },
        { id: 'field_dressing_hf', name: 'Field Dressing', description: 'Rough but effective — heals 1d6+2 HP', quantity: 2, effect: '1d6+2 HP', charges: 2, maxCharges: 2 },
        { id: 'oath_stone', name: 'Oath Stone', description: 'A piece of the mountain you swore on. Worthless to anyone else. Priceless to you.', quantity: 1 },
      ],
      startingCredits: 40,
      startingHp: 12,
      startingAc: 16,
      hitDieAvg: 6,
      trait: {
        name: 'Last Standing',
        description: 'Once per day, when reduced to 0 HP, drop to 1 HP instead and keep fighting.',
        usesPerDay: 1,
        usesRemaining: 1,
      },
      openingKnowledge: 'You know the weight of an oath sworn on stone and the weight of the axe that enforces it. A Stonemark Holdfast is a position, not a person: you are the place in the line that does not move. The clan trained you to hold ground the way they trained you to breathe, without thinking. The problem is that the world moves, and a position that does not move becomes either a fortress or an obstacle. Your companions value the first. Your enemies count on the second.',
    },
    {
      id: 'pactmaker',
      name: 'Pactmaker',
      concept: 'A Stonemark contract is unbreakable. That makes you the most trusted and most dangerous negotiator.',
      hookTags: ['schemer'],
      primaryStat: 'CHA',
      proficiencies: ['Persuasion', 'Insight', 'Noble Etiquette', 'Investigation'],
      stats: { STR: 12, DEX: 10, CON: 13, INT: 14, WIS: 11, CHA: 17 },
      startingInventory: [
        { id: 'stonemark_contract_kit', name: 'Contract Kit', description: 'Parchment, wax, clan seal. A Stonemark contract is recognized by every court in the provinces.', quantity: 1 },
        { id: 'oath_hammer', name: 'Oath Hammer', description: 'Ceremonial but solid — used to seal contracts on stone. Also functional in emergencies.', quantity: 1, damage: '1d6' },
        { id: 'precedent_book', name: 'Book of Precedents', description: 'Every major Stonemark contract of the last century. Advantage on checks involving contract law.', quantity: 1 },
        { id: 'clan_mead', name: 'Clan Mead', description: 'Shared at the sealing of a pact. Two servings.', quantity: 2 },
      ],
      startingCredits: 100,
      startingHp: 9,
      startingAc: 12,
      hitDieAvg: 4,
      trait: {
        name: 'Binding Word',
        description: 'Once per day, invoke a sworn agreement to compel its honoring or publicly expose a breach. The target must have made the agreement willingly. The Stonemark seal gives the invocation legal authority in any province.',
        usesPerDay: 1,
        usesRemaining: 1,
      },
      openingKnowledge: 'You know that a Stonemark word is the most valuable currency in the provinces, because it is the only one that cannot be debased. Every house, every lord, every merchant knows that a contract sealed by Stonemark will be honored to the letter. This makes you the most trusted negotiator in any room, and the most dangerous: a pact you write is a cage with no key. The other houses call this inflexibility. You call it the foundation of civilization. The question is what happens when the pact you wrote serves the letter of justice but not its spirit.',
    },
  ],
  'oathless': [
    {
      id: 'scavenger',
      name: 'Scavenger',
      concept: 'Freelance problem-solver. Takes jobs from all houses because sworn to none.',
      hookTags: ['inquisitor', 'hexblade'],
      primaryStat: 'INT',
      proficiencies: ['Investigation', 'Sleight of Hand', 'Survival', 'Lockpicking'],
      stats: { STR: 10, DEX: 14, CON: 12, INT: 17, WIS: 12, CHA: 11 },
      startingInventory: [
        { id: 'scavenger_tools', name: 'Scavenger\'s Tools', description: 'Lockpicks, pry bar, magnifying lens. The tools of someone who gets into things.', quantity: 1 },
        { id: 'concealed_blade_o', name: 'Concealed Blade', description: 'No markings, no house, no history', quantity: 1, damage: '1d4+DEX' },
        { id: 'salvage_pack', name: 'Salvage Pack', description: 'Miscellaneous useful items scavenged from previous jobs', quantity: 1 },
        { id: 'field_dressing_o', name: 'Field Dressing', description: 'Rough but effective — heals 1d6+2 HP', quantity: 2, effect: '1d6+2 HP', charges: 2, maxCharges: 2 },
      ],
      startingCredits: 60,
      startingHp: 8,
      startingAc: 13,
      hitDieAvg: 4,
      trait: {
        name: 'The Question',
        description: 'Once per day, after 1+ rounds of dialogue with a target, force a WIS save (DC = 8 + INT mod). On failure, the target reveals one true piece of information. On success, they know you tried. The Oathless variant: desperation, not authority. You ask because you need to know, not because you have the right.',
        usesPerDay: 1,
        usesRemaining: 1,
      },
      openingKnowledge: 'You know how institutions work because you used to be inside one, and you know how they fail because you fell through the gap. The Scavenger operates on institutional knowledge stripped of institutional protection: you understand house politics, Church procedure, mercenary contracts, because you\'ve been on the receiving end of all three. Nobody hires you for your name. They hire you because you\'re unaligned, which means your findings aren\'t shaped by whoever\'s paying your lord\'s bills. The freedom is real. So is the fact that nobody will protect you if the findings are inconvenient.',
    },
    {
      id: 'blade',
      name: 'Blade',
      concept: 'Fights without a banner. The violence is honest because it carries no oath behind it.',
      hookTags: ['cutthroat', 'ironclad'],
      primaryStat: 'DEX',
      proficiencies: ['Stealth', 'Athletics', 'Survival', 'Intimidation'],
      stats: { STR: 13, DEX: 17, CON: 14, INT: 10, WIS: 12, CHA: 10 },
      startingInventory: [
        { id: 'unmarked_sword', name: 'Unmarked Sword', description: 'No house insignia, no history, no allegiance', quantity: 1, damage: '1d8+DEX' },
        { id: 'throwing_knives_o', name: 'Throwing Knives', description: 'Balanced for throwing, 20ft range', quantity: 4, damage: '1d4' },
        { id: 'dark_cloak_o', name: 'Dark Cloak', description: 'Advantage on Stealth checks in dim light or darkness', quantity: 1, charges: 1, maxCharges: 1 },
        { id: 'field_dressing_bl', name: 'Field Dressing', description: 'Rough but effective — heals 1d6+2 HP', quantity: 2, effect: '1d6+2 HP', charges: 2, maxCharges: 2 },
      ],
      startingCredits: 50,
      startingHp: 10,
      startingAc: 15,
      hitDieAvg: 5,
      trait: {
        name: 'Marked',
        description: 'Once per day, designate a target as Marked. Your first hit against them deals +1d6 bonus damage.',
        usesPerDay: 1,
        usesRemaining: 1,
      },
      openingKnowledge: 'You know what violence looks like without a cause behind it, and you know that the honesty of that is both your curse and your selling point. Every house has sworn fighters. Every lord has retainers who kill on command and call it duty. You kill for coin and call it work. The difference is that you never pretend the violence serves something noble. Your sword has no insignia because you have no allegiance, and your price is public because your loyalty isn\'t for sale. The only honest killer in the provinces. The honesty doesn\'t make it clean.',
    },
    {
      id: 'whisper',
      name: 'Whisper',
      concept: 'Operates in the spaces between sworn factions. Trades information freely because loyalty would blind you.',
      hookTags: ['schemer', 'cutthroat'],
      primaryStat: 'CHA',
      proficiencies: ['Deception', 'Insight', 'Stealth', 'Persuasion'],
      stats: { STR: 10, DEX: 13, CON: 11, INT: 13, WIS: 12, CHA: 17 },
      startingInventory: [
        { id: 'cipher_ledger_w', name: 'Cipher Ledger', description: 'Contacts across every faction. No allegiance column.', quantity: 1 },
        { id: 'disguise_kit_w', name: 'Disguise Kit', description: 'Change appearance enough to pass casual inspection', quantity: 1, charges: 3, maxCharges: 3 },
        { id: 'concealed_blade_w', name: 'Concealed Blade', description: 'Hidden, unmarked, forgettable', quantity: 1, damage: '1d4' },
        { id: 'bribery_fund', name: 'Bribery Fund', description: 'Small purse of mixed-province crowns for loosening tongues', quantity: 1 },
      ],
      startingCredits: 110,
      startingHp: 8,
      startingAc: 12,
      hitDieAvg: 4,
      trait: {
        name: 'Leverage',
        description: 'Once per day, reveal a secret about a target NPC that changes the conversation. The Oathless variant: the secret was traded to you by someone in another faction, because the unsworn are the only people everyone talks to.',
        usesPerDay: 1,
        usesRemaining: 1,
      },
      openingKnowledge: 'You know what people say when they think the conversation is private, because the unsworn are the only people in the provinces that every faction talks to. Veldran merchants share trade intelligence because you\'re not sworn to a rival house. Stonemark soldiers confide because you carry no lord\'s banner. Church officials whisper because you have no doctrine to violate. Everyone trusts you with something because you belong to no one. The cipher ledger in your coat has no allegiance column because allegiance would destroy the only thing that makes you valuable: the fact that you hear everything and owe nothing.',
    },
  ],
  'house-ashfang': [
    {
      id: 'ember-scholar',
      name: 'Ember Scholar',
      concept: 'The Dominion had knowledge the other houses destroyed. You preserved fragments.',
      hookTags: ['hexblade', 'inquisitor'],
      primaryStat: 'INT',
      proficiencies: ['Forbidden Lore', 'Investigation', 'Hexcrafting', 'Corruption Resistance'],
      stats: { STR: 10, DEX: 13, CON: 12, INT: 17, WIS: 13, CHA: 10 },
      startingInventory: [
        { id: 'char_grimoire', name: 'Char Grimoire Fragment', description: 'Salvaged Dominion knowledge — advantage on Forbidden Lore checks', quantity: 1 },
        { id: 'hex_bolt_a', name: 'Hex Bolt', description: 'Ranged necrotic attack from Dominion fire-craft', quantity: 1, damage: '1d6 necrotic, range 30ft' },
        { id: 'binding_scroll_a', name: 'Binding Scroll', description: 'Restrain a target; DC 14 STR to break', quantity: 2 },
        { id: 'ash_vial', name: 'Vial of Dominion Ash', description: 'Component for Char-tradition hexcraft. Irreplaceable.', quantity: 3 },
      ],
      startingCredits: 60,
      startingHp: 8,
      startingAc: 12,
      hitDieAvg: 4,
      trait: {
        name: 'Corruption Tap',
        description: 'Once per day, auto-succeed on one forbidden magic check or inflict a minor curse. Each use darkens your reputation. The Ashfang variant: the magic is Char Dominion fire-craft, and the Church\'s reaction is ancestral hatred, not just institutional suspicion.',
        usesPerDay: 1,
        usesRemaining: 1,
      },
      openingKnowledge: 'You know what the Char Dominion knew before the other houses burned it. The grimoire fragments in your pack are evidence of a civilization that was destroyed for what it could do, not what it did. The Church calls Char knowledge heresy. The houses call it dangerous. You call it yours, because someone has to remember what was lost, and the Ashfang are the only ones who didn\'t help destroy it. The fire-craft in your hands carries three centuries of fear. Using it proves the fear was justified. Not using it lets the knowledge die.',
    },
    {
      id: 'charblood',
      name: 'Charblood',
      concept: 'The Dominion\'s fire in living form. Fast, imposing, terrifying.',
      hookTags: ['ironclad', 'cutthroat'],
      primaryStat: 'STR',
      proficiencies: ['Athletics', 'Intimidation', 'Initiative', 'Survival'],
      stats: { STR: 17, DEX: 13, CON: 15, INT: 10, WIS: 11, CHA: 10 },
      startingInventory: [
        { id: 'char_greatsword', name: 'Char Greatsword', description: 'Dominion-pattern blade, black iron, feared on sight', quantity: 1, damage: '1d12' },
        { id: 'spiked_bracers', name: 'Spiked Bracers', description: '+1 AC, can be used as improvised weapon (1d4)', quantity: 1 },
        { id: 'field_dressing_a', name: 'Field Dressing', description: 'Rough but effective — heals 1d6+2 HP', quantity: 2, effect: '1d6+2 HP', charges: 2, maxCharges: 2 },
        { id: 'dominion_token', name: 'Dominion Token', description: 'A relic from the Char era. Ashfang recognize it. Everyone else fears it.', quantity: 1 },
      ],
      startingCredits: 40,
      startingHp: 12,
      startingAc: 15,
      hitDieAvg: 6,
      trait: {
        name: 'Last Standing',
        description: 'Once per day, when reduced to 0 HP, drop to 1 HP instead and keep fighting. The Ashfang variant: rage-fueled. The Dominion\'s fire burns in the blood.',
        usesPerDay: 1,
        usesRemaining: 1,
      },
      openingKnowledge: 'You know the fear before you see it; you feel it in the way a room changes when you enter. The Char Dominion burned three centuries ago, but the provinces remember the fire, and you carry it in your face, your build, your name. The Charblood is what the other houses imagined when they destroyed the Dominion: a warrior too fast, too strong, too willing to use what the blood provides. You are the nightmare they told themselves justified the genocide. The question you carry is whether the nightmare is a description of what you are or a cage the other houses built for you.',
    },
    {
      id: 'exile-voice',
      name: 'Exile Voice',
      concept: 'Speaks for scattered Ashfang. Negotiates from a position of ancestral injury.',
      hookTags: ['schemer', 'plague-doctor'],
      primaryStat: 'CHA',
      proficiencies: ['Persuasion', 'Insight', 'Medicine', 'Survival'],
      stats: { STR: 10, DEX: 12, CON: 13, INT: 12, WIS: 14, CHA: 17 },
      startingInventory: [
        { id: 'ashfang_ledger', name: 'Exile Ledger', description: 'Names, locations, and debts of scattered Ashfang communities', quantity: 1 },
        { id: 'medicinal_tinctures_ev', name: 'Medicinal Tinctures', description: 'Ashfang remedies — heals 1d8+WIS HP', quantity: 1, effect: '1d8+WIS HP', charges: 3, maxCharges: 3 },
        { id: 'antidote_kit_ev', name: 'Antidote Kit', description: 'Neutralize poisons and contagions', quantity: 1, charges: 2, maxCharges: 2 },
        { id: 'ceremonial_dagger_ev', name: 'Ceremonial Dagger', description: 'Char Dominion pattern — a symbol of office, not just a weapon', quantity: 1, damage: '1d4' },
      ],
      startingCredits: 80,
      startingHp: 9,
      startingAc: 12,
      hitDieAvg: 5,
      trait: {
        name: 'Bitter Medicine',
        description: 'Once per day, heal an ally for 1d8+WIS, but the treatment has a side effect chosen by the GM. The Ashfang variant: the medicine is Dominion-tradition, which means it works and it frightens people. Patients healed by Ashfang methods carry a stigma.',
        usesPerDay: 1,
        usesRemaining: 1,
      },
      openingKnowledge: 'You know every scattered Ashfang community between the mountains and the coast, because someone has to. The Exile Voice speaks for a people dispersed across provinces that burned their homeland, negotiating from a position of ancestral injury that the other houses would prefer to forget. You heal because the Dominion\'s medical traditions survived the burning, and because arriving with medicine opens doors that arriving with anger closes. The ledger in your pack maps what\'s left of a people: names, locations, children, debts. Every entry is someone who survived what the provinces did. Every negotiation carries that weight.',
    },
  ],
  'church-raised': [
    {
      id: 'inquisitor',
      name: 'Inquisitor',
      concept: 'The Church\'s investigative arm. Sanctioned interrogator who determines moral legitimacy.',
      hookTags: ['inquisitor'],
      primaryStat: 'INT',
      proficiencies: ['Interrogation', 'Investigation', 'Intimidation', 'Anatomy'],
      stats: { STR: 11, DEX: 12, CON: 13, INT: 17, WIS: 14, CHA: 10 },
      startingInventory: [
        { id: 'inquisitors_seal_cr', name: 'Inquisitor\'s Seal', description: 'Institutional authority; advantage on Intimidation when shown', quantity: 1 },
        { id: 'iron_pincers_cr', name: 'Iron Pincers', description: 'Interrogation tool; +2 to Interrogation checks', quantity: 1 },
        { id: 'journal_confessions_cr', name: 'Journal of Confessions', description: 'Detailed notes; advantage on Investigation checks against known subjects', quantity: 1 },
        { id: 'stiletto_cr', name: 'Stiletto', description: 'Concealed blade, always on person', quantity: 1, damage: '1d4+DEX' },
      ],
      startingCredits: 90,
      startingHp: 9,
      startingAc: 13,
      hitDieAvg: 5,
      trait: {
        name: 'The Question',
        description: 'Once per day, after 1+ rounds of dialogue with a target, force a WIS save (DC = 8 + INT mod). On failure, the target reveals one true piece of information. On success, they know you tried.',
        usesPerDay: 1,
        usesRemaining: 1,
      },
      openingKnowledge: 'You know the weight of a question asked with institutional authority and the silence after someone realizes you have the power to make them answer. The Church gave you a seal, a mandate, and the belief that what you do is necessary. You don\'t investigate crimes; you investigate moral legitimacy. Did this lord deserve to survive the war? Did this village earn the peace? The answers are never simple, and the Inquisition doesn\'t require simplicity. It requires a verdict. Your predecessor\'s last case file sits unopened in your satchel. He said to start over.',
    },
    {
      id: 'crusader',
      name: 'Crusader',
      concept: 'The Pale Flame\'s martial arm. Faith expressed as violence, duty as devotion.',
      hookTags: ['ironclad'],
      primaryStat: 'STR',
      proficiencies: ['Athletics', 'Intimidation', 'Heavy Weapons', 'Shield Tactics'],
      stats: { STR: 17, DEX: 12, CON: 15, INT: 10, WIS: 12, CHA: 10 },
      startingInventory: [
        { id: 'pale_flame_hammer', name: 'Pale Flame Warhammer', description: 'Church-consecrated, the Flame etched into the head', quantity: 1, damage: '1d10' },
        { id: 'crusader_shield', name: 'Crusader\'s Shield', description: '+2 AC — the Church\'s sunburst blazoned on the face', quantity: 1 },
        { id: 'field_dressing_cr', name: 'Church Field Kit', description: 'Blessed bandages — heals 1d6+2 HP', quantity: 2, effect: '1d6+2 HP', charges: 2, maxCharges: 2 },
        { id: 'writ_of_passage', name: 'Writ of Passage', description: 'Church-issued travel authorization; opens gates in any province', quantity: 1 },
      ],
      startingCredits: 60,
      startingHp: 12,
      startingAc: 16,
      hitDieAvg: 6,
      trait: {
        name: 'Last Standing',
        description: 'Once per day, when reduced to 0 HP, drop to 1 HP instead and keep fighting.',
        usesPerDay: 1,
        usesRemaining: 1,
      },
      openingKnowledge: 'You know the weight of a hammer consecrated by the Pale Flame and the sound it makes when it lands on someone the Church has judged. The sound is the same as any other hammer. That\'s the point: the consecration is in the authority, not the metal. You were trained to fight for doctrine, which in practice means fighting for the institution. The difference between those two things was clear when you took your vows. It is less clear now. The writ of passage in your belt pouch opens every gate in every province. What you do after the gate opens is between you and the Flame.',
    },
    {
      id: 'shepherd',
      name: 'Shepherd',
      concept: 'The Church\'s gentle face. Heals the sick, feeds the hungry, and knows everything because they trusted you.',
      hookTags: ['plague-doctor'],
      primaryStat: 'WIS',
      proficiencies: ['Medicine', 'Perception', 'Insight', 'Persuasion'],
      stats: { STR: 10, DEX: 13, CON: 14, INT: 12, WIS: 17, CHA: 11 },
      startingInventory: [
        { id: 'shepherd_kit', name: 'Shepherd\'s Kit', description: 'Medical supplies and pastoral tools — heals 1d8+WIS HP', quantity: 1, effect: '1d8+WIS HP', charges: 3, maxCharges: 3 },
        { id: 'antidote_kit_sh', name: 'Antidote Kit', description: 'Neutralize poisons, venoms, and early-stage contagion', quantity: 1, charges: 2, maxCharges: 2 },
        { id: 'confessional_journal', name: 'Confessional Journal', description: 'Encrypted pastoral notes. What people tell you in confidence, catalogued for the institution.', quantity: 1 },
        { id: 'walking_staff', name: 'Walking Staff', description: 'Solid oak, practical, unassuming', quantity: 1, damage: '1d6' },
      ],
      startingCredits: 70,
      startingHp: 10,
      startingAc: 13,
      hitDieAvg: 5,
      trait: {
        name: 'Bitter Medicine',
        description: 'Once per day, heal an ally for 1d8+WIS, but the treatment has a side effect chosen by the GM: nausea, hallucinations, or dependency. Nothing is free.',
        usesPerDay: 1,
        usesRemaining: 1,
      },
      openingKnowledge: 'You know what people look like when they believe you can help, and you know that the belief is the first instrument. The Church trained you to heal, to feed, to listen. The listening is the part they don\'t mention in the training manuals: every confession, every bedside conversation, every tearful admission flows through you to the institution. You are the Church\'s eyes in every village, every camp, every household that opens its door to a healer. The care is genuine. The reporting is also genuine. The gap between those two facts is where you live, and it narrows every time someone trusts you with something you\'re obligated to pass along.',
    },
  ],
}

const grimdarkConfig: GenreConfig = {
  id: 'grimdark',
  name: 'Grimdark',
  tagline: 'Kingdoms rot from the inside. Someone has to survive it.',
  available: true,
  species: grimdarkSpecies,
  speciesLabel: 'Bloodline',
  classes: grimdarkClasses,
  playbooks: grimdarkPlaybooks,
  theme: grimdarkTheme,
  currencyName: 'crowns',
  currencyAbbrev: 'cr',
  partyBaseName: 'Company',
  settingNoun: 'world',
  systemPromptFlavor: {
    role: 'You are the Game Master of Storyforge — a solo text RPG set in a crumbling medieval world where empires rot and survival is political.',
    setting: `The Shattered Provinces have held peace for a generation, but the Pact of Ashes is fraying. A famine called the Wasting spreads from the southern provinces, crops failing and livestock dying without explanation. Border lords raise private armies. The Church of the Pale Flame burns reformers and calls it salvation. Something stirs beneath the old ruins that predate every kingdom alive today.

This is a world of moral compromise, political betrayal, hard winters, and bodies in the mud. The player commands a small mercenary company navigating a world where old allegiances mean less every week.

Weapons: swords, axes, crossbows, bows, knives, polearms. No guns. Magic exists but is feared, costly, and rarely clean. No potions — medicinal tinctures, field dressings, antidote kits. Gold, not credits.

Vocabulary (never use sci-fi terms; fantasy terms that imply heroism should be used sparingly):
- Spell → hex / curse / forbidden working / corrupted craft
- Potion → tincture / salve / kit / vial
- Quest → contract / job / commission
- Party → company / crew / band
- Inn → tavern / waystation / camp
- Temple → keep / monastery / shrine`,
    vocabulary: `Consumable terminology: tinctures, field dressings, antidote kits, toxin vials.
Rest terminology: Short rest, Long rest. Tone: bleak, morally ambiguous, politically complex. Victories are never clean.`,
    tutorialContext: 'Open in a burned village, a tavern with a wanted poster, or the aftermath of a skirmish. Introduce a morally complex NPC early — someone who needs the company but cannot be fully trusted.',
  },
  promptSections: {
    role: 'You are the Game Master of a grimdark tabletop RPG campaign. You narrate a world where power corrupts, mercy is expensive, and the line between hero and monster is drawn in mud and blood.',
    setting: 'The Shattered Provinces have held an uneasy peace under the Pact of Ashes, but the treaty is fraying. A famine called the Wasting creeps from the southern provinces. The Church of the Pale Flame controls hospitals, orphanages, and the Inquisition. Kingdoms are corrupt or tyrannical. Magic is rare, feared, and forbidden — those who wield it pay a visible price. The common people suffer regardless of who rules. Moral clarity is a luxury.',
    vocabulary: 'Use blunt, physical language: mud, blood, iron, rot. Violence has weight. Death is ugly. Healing is slow. Magic is unsettling. Currency is crowns. Dialogue is direct, often crude. Titles used with irony as often as respect. Spell = hex / curse / forbidden working / corrupted craft. Potion = tincture / salve / kit / vial. Quest = contract / job / commission. Party = company / crew / band. Inn = tavern / waystation / camp. Temple = keep / monastery / shrine.',
    toneOverride: 'Adjust tone: Gritty (60%), Epic (25%), Witty (15%). Grandeur exists but is tarnished — a crumbling cathedral, a once-great army reduced to mercenaries. Humor is dark, sharp, and necessary.',
    assetMechanic: `## THE COMPANY\n\nThe company is your mercenary band. Five dimensions tracked at L1-L3:\n- Strength: fighters, equipment, combat capability. Upgrade through recruitment and victories.\n- Morale: will to fight, unit cohesion under pressure. Upgrade through paid contracts and victories. Degrades without pay or after defeats.\n- Reputation: who knows you, whether they hire or avoid. Upgrade through visible successes. Damaged by broken contracts.\n- Intelligence: scouts, informants, advance warning. Upgrade through recruiting specialists.\n- Provisions: supplies, medical stores, operational endurance. Consumed by operations. Replenished by contracts.\n\nThe company degrades between chapters without maintenance. Propose 2-3 ways to maintain or upgrade the company at chapter transitions.\n\nEach dimension should have a named NPC attached (the sergeant, the quartermaster, the scout, etc.). Upgrading a dimension means investing in the person who runs it.`,
    traitRules: `## TRAIT RULES\n\n- **Corruption Tap:** Each use darkens reputation. Cumulative, never resets. The Hexblade's power has a permanent social cost.\n- **Leverage:** Requires prior interaction or intel. Secret cuts both ways. The target remembers, and the relationship is permanently changed.\n- **Bitter Medicine:** Every heal has a side effect: nausea, hallucinations, or dependency. The GM chooses. Nothing is free.\n- **The Question:** Requires 1+ rounds of dialogue. WIS save failure reveals one truth. Success: they know you tried. Failed interrogations have social consequences.\n- **Marked:** Designate one target per day. First hit deals +1d6 bonus damage. The choice of who to mark is the moral weight.\n- **Last Standing:** Drop to 1 HP instead of 0, once per day. No strings. Reliability is the point.\n- **Binding Word:** Invoke a sworn agreement to compel its honoring or expose a breach. The target must have made the agreement willingly. The Stonemark seal gives legal authority in any province. The words you bind others with also bind you.`,
    consumableLabel: 'Poultices, blasting powder, antitoxin, bandages',
    tutorialContext: 'The opening chapter introduces a morally compromised situation, one conditional NPC, and a job where success and failure both cost. First check: social or investigation. First combat: human enemies. Open in a burned village, a tavern with a wanted poster, or the aftermath of a skirmish. Introduce a morally complex NPC early — someone who needs the company but cannot be fully trusted.',
    npcVoiceGuide: 'Mercenaries: gallows humor, fatalistic. Nobles: self-justifying, every order framed as necessity. Priests: fervent or exhausted. Informants: paranoid, transactional. Common folk: resigned, distrust anyone with power.',
    buildAssetState: (ship, shipName) => {
      const systemsLine = ship.systems.map(s => `${s.name} L${s.level}: ${s.description}`).join('\n  ')
      const combatLine = ship.combatOptions.length > 0 ? ship.combatOptions.join(', ') : 'None'
      return `\nCOMPANY: ${shipName}\n  ${systemsLine}\nCOMPANY TACTICS: ${combatLine}`
    },
    investigationGuide: `Journal of confessions — extracted testimony, names implicated, evidence of heresy or corruption.

Evidence is coerced, not discovered. Confessions come under pressure, testimony is traded for favors, documents are stolen rather than filed. Nobody volunteers the truth in this world — it has to be extracted, and extraction changes the relationship.

The faction clock is survival, not politics. The longer you investigate, the more dangerous it gets — witnesses die, evidence is burned, the target sends people after you. Every turn spent gathering evidence is a turn the target spends covering tracks.

Misdirection comes from NPCs lying for their own reasons, not from planted evidence. Everyone has a version of the truth that serves their interests. When testimonies contradict, the contradiction is itself a clue about who benefits from which version.

The gatekeeper clue is a person, not a document. Someone who knows the truth and will only share it for a price the player may not want to pay. The price is always moral, not financial.`,
  },
  deepLore: `## THE SHATTERED PROVINCES

**The Pact of Ashes.** Forty years ago, the War of Wyrms ended with the destruction of the Char Dominion and the near-ruin of everyone involved. The Pact of Ashes was the treaty: borders frozen, reparations set, a mutual exhaustion agreement dressed as peace. It held because everyone was too broken to fight. A generation has healed. The borders feel wrong now. The reparations feel unjust to the payers and insufficient to the payees. The Pact is not breaking from a single cause; it is rotting from accumulated resentment. Every lord has a reason to break it. None will admit to being first.

**The Church of the Pale Flame.** The only institution that spans all provinces. Controls hospitals, orphanages, and the Inquisition. The Church's power is practical, not theological: they feed the hungry, heal the sick, and educate the children. This earns a loyalty no army can match. The Inquisition enforces doctrinal compliance, which in practice means political compliance: heresy charges are the Church's tool for removing inconvenient people. The Church believes sincerely in its mission. It also believes sincerely that maintaining its power is necessary for that mission. Both beliefs are true, and the gap between them is where corruption lives.

**The Wasting.** A famine spreading from the southern provinces. Crops fail, livestock die, and the soil turns grey. Not a natural blight; the pattern is too precise, moving along roads and rivers rather than wind. Someone or something is causing it. The provinces blame each other. The Church calls it divine judgment. The actual cause is unknown, and every theory serves the political needs of whoever proposes it.

**House Politics.** Five landed houses and two factions outside them control the provinces. House Veldran (merchant nobility, wealth is power) dominates trade. House Sylvara (ancient woodland bloodline, patience as weapon) controls the northern forests. House Stonemark (mountain clan, their word is their bond) holds the mountain passes. House Ashfang (fallen bloodline of the Char Dominion, feared and distrusted) survives in exile. The Oathless are the unsworn: people who refuse to take oaths in a world built on them, operating freely because they owe nothing and trusted by no one because they swear to no one. The Church of the Pale Flame stands above the houses as the only pan-provincial institution, its Inquisition and hospitals reaching where no lord's authority can. Inter-house politics is a slow knife fight conducted through marriages, trade agreements, and the occasional assassination.

**The Mercenary Economy.** The Pact of Ashes forbids standing armies above a treaty-specified size. The loophole: mercenary companies. Every lord employs them. The companies are nominally independent; in practice, everyone knows which lord feeds which company. The player's company operates in this gray zone: too valuable to dismiss, too expendable to protect. Contracts are the company's oxygen. No contract, no provisions, no morale, no company.

**The Old Ruins.** Beneath the provinces, older than any house, are ruins that predate the human settlement of these lands. The Church declares them heretical. The houses want what is inside. The things inside do not care about either. Magic drawn from the ruins is forbidden by the Church, practiced in secret by the houses, and more dangerous than either admits. The Hexblade knows this firsthand.`,
  guideNpcDirective: 'The opening NPC is someone who needs the company but cannot fully trust them. They speak like a person calculating whether hiring mercenaries will solve their problem or become their next problem. They do not explain the world; they present a job, and the terms of the job reveal how the world works.',
  loreFacets: {
    political: 'In this scene: every lord is calculating how the Pact benefits them if it breaks, and positioning accordingly. Hospitality is surveillance. Offers come with conditions you discover later. The smile means they need something; the frown means they have it.',
    church: 'In this scene: the Church feeds the hungry and burns the heretic with the same conviction. Officials believe they are doing good. They are. They are also removing threats to their institutional power and calling it salvation. Watch for the moment care becomes control, the shift from "we want to help" to "you will be helped."',
    company: 'In this scene: the company is a family held together by pay and shared survival. Morale is fragile. Soldiers have opinions about the captain\'s choices and share them by firelight. A shared meal matters more than a speech. The sergeant\'s mood tells you more than any report.',
    battlefield: 'In this scene: violence is ugly, specific, and has a smell. Soldiers fight for pay, not causes. The aftermath is worse than the fight: mud, groaning, the decision of what to do with prisoners. Victory is a transaction, not a triumph.',
    wasting: 'In this scene: the land is dying. Grey soil, dead livestock, empty granaries. People are thin. Children stare. The Wasting is not dramatic; it is mundane. It is the absence of food where food used to be. The political arguments about its cause feel obscene when you are standing in a field that will not grow.',
    ruin: 'In this scene: the air tastes of copper and wrong. The Church says these places are heretical. The houses want what is inside. The things inside predate both. Magic here costs more than fatigue; it costs reputation, sanity, and the certainty that you understand what you are touching. The Hexblade feels it first.',
  },
  loreAnchors: [
    'Pact of Ashes=forty years old. Borders frozen, reparations set. Rotting from accumulated resentment. Every lord has a reason to break it.',
    'Church of the Pale Flame=only institution spanning all provinces. Hospitals + orphanages + Inquisition. Lie by theology ("The Flame reveals all"). Power from service.',
    'The Wasting=famine spreading from the south. Pattern is too precise for nature. Every theory serves the theorist\'s politics.',
    'House Veldran=merchant nobility. Wealth is power. Lie by negotiation ("That depends on the terms"). Everyone assumes you\'re buying loyalty.',
    'House Sylvara=ancient woodland. Patience as weapon. Lie by omission (they wait for you to fill the silence). Courts respect, frontiers suspect.',
    'House Stonemark=mountain clan. Word is bond. Cannot lie (cultural, not magical). Bluntness reads as insult to everyone else.',
    'House Ashfang=fallen Char Dominion. Feared. Church is hostile. Lie by reputation (they let fear do the talking).',
    'The Oathless=the unsworn. Refuse to take oaths in a world built on them. Free because they owe nothing. Distrusted because they swear to nothing. Every faction talks to them; none trusts them.',
    'Church-Raised=trained by the Pale Flame. Sincere conviction + institutional machinery. The gap between mission and power is where they live. Lie by doctrine ("The Flame reveals what is necessary").',
    'Mercenary economy=standing armies capped by treaty. Everyone uses companies. Contracts are oxygen. No contract, no company.',
    'Crowns (cr)=provincial currency. Value varies by region. The Wasting is causing inflation in the south. Northern crowns buy more.',
  ],
  cohesionGuide: 'In this genre, cohesion is conditional loyalty maintained by results. +1: successful contracts paid in full, captain taking risks the company needed, victories that vindicate hard choices. -1: broken contracts, mission failures the captain pushed for, mercy that costs the company resources or lives. Cohesion is brittle — it can be high but never feels secure, because the next failed contract could break it. The company degrades between chapters without maintenance.',
  companionLabel: 'Sworn',
  notebookLabel: 'Journal',
  intelTabLabel: 'Dossier',
  intelNotebookLabel: 'Evidence',
  intelOperationLabel: 'Scheme',
  explorationLabel: 'Ground',
  openingHooks: [
    // ── Universal (5) — work for any origin ──
    { hook: 'The battle is over. The wrong side won. The company\'s employer is dead, and the victors are offering amnesty to surrendering mercenaries. The kind that ends with a noose.', title: 'Wrong Side', frame: { objective: 'Get the company out before the amnesty closes', crucible: 'Surrender means death with a different name, and the victors are tightening the cordon' }, arc: { name: 'The Wrong Side', episode: 'Escape the battlefield and find shelter before the victors organize pursuit' } },
    { hook: 'A courier brings payment for a job the company didn\'t do. Someone is using the company\'s name — and whoever hired them wants a reckoning.', title: 'Stolen Name', frame: { objective: 'Find who\'s using the company\'s name', crucible: 'Someone else\'s work is attached to your reputation, and the client wants answers' }, arc: { name: 'The Stolen Name', episode: 'Meet the angry client and trace the impostor\'s last known operation' } },
    { hook: 'A child walks into camp alone, carrying a signet ring from a dead lord. She won\'t say where she got it — only: "They said to find the Company."', title: 'The Signet Ring', frame: { objective: 'Discover who sent the child and what the ring means', crucible: 'A dead lord\'s signet in a child\'s hand, delivered to mercenaries by name' }, arc: { name: 'The Signet Ring', episode: 'Identify the signet, question the child, and decide whether to follow the trail' } },
    { hook: 'Mid-winter. The road north is blocked by snow. The only shelter: an abandoned monastery. Inside, a group of deserters from the losing side of last month\'s battle — wounded, starving, armed, and terrified. They don\'t want to fight. They want to survive the winter. But the company needs the shelter too, and there isn\'t enough food for both groups. The deserters\' leader offers a deal: share the monastery until the thaw, and she\'ll tell you which lord is marching south with the army that just won.', title: 'The Monastery', frame: { objective: 'Decide whether to share the monastery or take it', crucible: 'Desperate people with intelligence you need, not enough food for both, and winter closing in' }, arc: { name: 'The Winter Monastery', episode: 'Negotiate with the deserters and assess whether sharing is survivable' } },
    { hook: 'Three days ago, the company freed prisoners from a lord\'s dungeon. Good deed, clear conscience. This morning, two of them killed — one a rival, one an innocent witness. The lord\'s steward found you: "He wasn\'t keeping them in cages because he\'s cruel. He was keeping them in cages because he knew what they\'d do." Now the lord wants compensation, the dead witness\'s family wants justice, and two of the freed prisoners are asking for the company\'s protection.', title: 'The Mercy', frame: { objective: 'Settle the reckoning before it buries the company', crucible: 'Your good deed produced two corpses, and three parties want different kinds of payment' }, arc: { name: 'The Price of Mercy', episode: 'Face the lord\'s steward and the witness\'s family, and decide what justice looks like' } },
    // ── Veldran (3) — wealth as power, information as commodity ──
    { hook: 'A sealed contract arrives from a house that doesn\'t officially exist. Payment is generous. The task: enter a lord\'s bedchamber and replace his medicine with something from a black vial. They don\'t want it to look like poison. They want it to look like God.', title: 'The Black Vial', origins: ['house-veldran'], classes: ['Broker'], frame: { objective: 'Get inside the lord\'s chambers and make the switch', crucible: 'A ghost house paying for a death that must look divine, not criminal' }, arc: { name: 'The Black Vial', episode: 'Infiltrate the lord\'s household and assess the security around his chambers' } },
    { hook: 'A lord hires the company to investigate missing grain shipments. The trail leads to the lord\'s own steward. The steward offers you triple to say you found nothing. The lord\'s wife offers you something else entirely to make the steward disappear.', title: 'Three Offers', origins: ['house-veldran'], classes: ['Broker', 'Assessor'], frame: { objective: 'Choose whose offer to take — or play all three', crucible: 'Three parties bidding against each other for your loyalty, and the truth is leverage' }, arc: { name: 'Three Offers', episode: 'Investigate the grain trail and map who benefits from each possible outcome' } },
    { hook: 'Two houses are negotiating a marriage alliance. Both have hired you separately — one to ensure the marriage happens, the other to ensure it doesn\'t. You took both contracts because you knew you\'d learn more from the middle than either side.', title: 'Both Contracts', origins: ['house-veldran'], classes: ['Broker'], frame: { objective: 'Control the negotiation from the middle', crucible: 'Two opposing contracts, both trusting you, and the information advantage only lasts until someone talks' }, arc: { name: 'Both Contracts', episode: 'Attend the first negotiation session and map each house\'s real priorities' } },
    // ── Sylvara (3) — patience as weapon, long view ──
    { hook: 'A border dispute between Veldran and Stonemark has been simmering for nine years. Both sides have asked Sylvara to arbitrate. The previous arbiter died of old age before reaching a verdict. You have the file. On page forty, a note in the dead arbiter\'s hand: "Both sides are lying about the same corpse." The hearing resumes tomorrow.', title: 'The Ninth Year', origins: ['house-sylvara'], classes: ['Arbiter', 'Watcher'], frame: { objective: 'Find the corpse both sides are lying about before the hearing', crucible: 'Nine years of accumulated testimony built on a shared lie, and a hearing that resumes in hours' }, arc: { name: 'The Ninth Year', episode: 'Read the dead arbiter\'s file and identify which testimony contradicts which' } },
    { hook: 'A Sylvara watchtower on the northern border has gone silent. Not attacked; silent. The rotation arrived to find the tower intact, supplies untouched, and the three watchers gone. Their observation journal ends mid-sentence: "The pattern in the treeline is not —" The northern forests predate the houses. Things move in them that Sylvara has watched for centuries without understanding.', title: 'The Silent Tower', origins: ['house-sylvara'], classes: ['Thornguard', 'Watcher'], frame: { objective: 'Investigate the watchtower and find the missing observers', crucible: 'Three vanished watchers, an unfinished observation, and a forest that has been watching back' }, arc: { name: 'The Silent Tower', episode: 'Examine the tower, read the observation journal, and enter the treeline' } },
    { hook: 'You\'ve been watching a Veldran trade convoy for six weeks, documenting a pattern of grain diversions that, if proven, would break the house\'s trade monopoly. Tonight the evidence is complete. Tomorrow you can present it to the provincial court. Then the convoy\'s guard captain finds you and says: "We know what you have. We also know that the grain is feeding three villages the Wasting would have killed. Expose us and the villages starve. Is your evidence worth more than their harvest?"', title: 'The Harvest', origins: ['house-sylvara'], classes: ['Watcher', 'Arbiter'], frame: { objective: 'Decide what to do with evidence that is both just and lethal', crucible: 'Six weeks of patient work, proof of corruption, and three villages that survive because of it' }, arc: { name: 'The Harvest', episode: 'Verify the guard captain\'s claim about the villages before deciding' } },
    // ── Stonemark (3) — oath as identity, breaking vs. holding ──
    { hook: 'The bridge at Ashford is the only crossing for fifty miles, and two armies want it. Your company holds it — not by contract, but because you were standing on it when the war started. Both sides have sent envoys. Both want you to hold it for them. Neither is offering enough.', title: 'The Bridge', origins: ['house-stonemark'], classes: ['Holdfast'], frame: { objective: 'Choose a side or hold the bridge alone', crucible: 'Two armies, one bridge, no contract, and a position that\'s only valuable until someone takes it' }, arc: { name: 'The Bridge at Ashford', episode: 'Hear both envoys and assess which army is the greater threat' } },
    { hook: 'A Stonemark contract was signed thirty years ago between two lords. One is dead. The other wants the contract voided. The dead lord\'s heir says the contract is valid. You wrote the contract, or rather, a Pactmaker in your lineage did. Both sides want you to interpret the ambiguous clause on page three. The clause was ambiguous on purpose. The Pactmaker who wrote it knew exactly what they were doing. You found their notes. The intended interpretation would ruin the living lord. The heir doesn\'t know the notes exist.', title: 'Page Three', origins: ['house-stonemark'], classes: ['Pactmaker'], frame: { objective: 'Interpret the contract knowing the original intent', crucible: 'A thirty-year-old trap disguised as a clause, and the person it was meant for is sitting across from you' }, arc: { name: 'Page Three', episode: 'Read the Pactmaker\'s notes and determine what the ambiguous clause was designed to do' } },
    { hook: 'The company\'s last contract ended when the employer broke the terms: he asked you to burn a granary to starve a rival village into submission. You refused. He withheld payment. By Stonemark reckoning, he owes you double. By provincial law, mercenaries who abandon contracts are outlaws. The lord has filed charges. Your company has three days of provisions. The lord\'s granary is still standing, and the rival village is still eating. For now.', title: 'The Broken Terms', origins: ['house-stonemark'], classes: ['Holdfast', 'Sapper'], frame: { objective: 'Recover the owed payment or find a new contract before provisions run out', crucible: 'A lord who broke faith, a legal system that punishes the wronged, and three days of food' }, arc: { name: 'The Broken Terms', episode: 'Assess legal options and decide whether to pursue the debt or cut losses' } },
    // ── Oathless (3) — the unsworn, freedom as position ──
    { hook: 'The mark is dead. Clean work. Then the client sends a second name — the dead man\'s daughter, twelve years old. She saw something. The client says it\'s the job. Your gut says it\'s a test.', title: 'Second Name', origins: ['oathless'], classes: ['Blade'], frame: { objective: 'Find the girl and decide her fate yourself', crucible: 'A child witness, a client testing your limits, and a line you have to define' }, arc: { name: 'The Second Name', episode: 'Locate the girl and learn what she actually saw' } },
    { hook: 'Three factions have approached you in the same week: a Veldran agent wants intelligence on Stonemark troop movements. A Church official wants the name of the Ashfang cell operating in the southern province. A Stonemark pactmaker wants to know what Veldran offered you. All three are paying. None knows about the others. You could serve one, play two against each other, or sell all three the same carefully edited version of the truth. The problem: one of the three already knows you\'ve been approached by the others. You don\'t know which one.', title: 'Three Factions', origins: ['oathless'], classes: ['Whisper'], frame: { objective: 'Navigate the triple approach without being caught', crucible: 'Three factions, three payments, and one of them already knows more than they should' }, arc: { name: 'Three Factions', episode: 'Determine which faction knows about the others and what they plan to do with that knowledge' } },
    { hook: 'Someone is killing with your methods — same blade angle, same entry point, same calling card you stopped using years ago. Two dead this week. The city watch doesn\'t know your face yet, but whoever is copying your work wants them to.', title: 'Your Methods', origins: ['oathless'], classes: ['Blade', 'Scavenger'], frame: { objective: 'Find the copycat before the watch finds you', crucible: 'Your retired signature is being used to frame you, and the bodies are piling up' }, arc: { name: 'Your Methods', episode: 'Examine the kills, identify what the copycat got right, and track their mistakes' } },
    // ── Ashfang (3) — fear as inheritance, forbidden knowledge ──
    { hook: 'A village burned its own healer at the stake for witchcraft. The healer\'s apprentice found you and says the real curseworker is still in the village, hiding behind the accusation. The plague that started before the burning is getting worse. They need someone who understands forbidden things. You\'re Ashfang. You understand forbidden things. And the village that needs your help is the same village that burned an Ashfang shrine twenty years ago.', title: 'The Real Curse', origins: ['house-ashfang'], classes: ['Ember Scholar'], frame: { objective: 'Find the real curseworker before the plague spreads further', crucible: 'The village killed the wrong person, the curse is accelerating, and you\'re the kind of help they fear most' }, arc: { name: 'The Real Curse', episode: 'Enter the village, examine the plague, and identify the true source of the hex' } },
    { hook: 'Your focus cracked last night. Not from use — from something pushing out. The bone fetish is warm, and the markings have changed. Whatever was bound inside is awake, and it\'s been whispering a name. Yours. The markings are Char Dominion script, older than the Pact of Ashes. Whatever is inside the fetish remembers the Dominion, and it thinks you\'re someone else.', title: 'Something Inside', origins: ['house-ashfang'], classes: ['Ember Scholar'], frame: { objective: 'Contain or communicate with whatever woke inside the focus', crucible: 'Your primary tool is compromised, and the thing inside remembers a civilization everyone else destroyed' }, arc: { name: 'Something Inside', episode: 'Stabilize the cracked focus and determine what was bound in it' } },
    { hook: 'An Ashfang settlement in the eastern marches has been raided. Not by soldiers; by Church agents, operating under an Inquisition warrant for "heretical artifacts." The artifacts are Char Dominion medical texts. The settlement\'s healer used them to treat Wasting symptoms when the Church\'s own remedies failed. The healer is in a Church holding cell. The texts are scheduled for burning. The settlement has asked you to get them back — the texts, and the healer. The Church considers both contaminated.', title: 'Contaminated', origins: ['house-ashfang'], classes: ['Exile Voice', 'Charblood'], frame: { objective: 'Recover the healer and the medical texts before the Church burns both', crucible: 'Dominion knowledge that saves lives, a Church that calls it heresy, and a healer in a cell' }, arc: { name: 'Contaminated', episode: 'Locate the holding cell and assess the Church garrison\'s strength' } },
    // ── Church-Raised (3) — doctrine vs. conscience, moral legitimacy ──
    { hook: 'The church sends you to a remote monastery to investigate reports of heresy. When you arrive, the abbot is cooperative, the brothers are devout, and the chapel is immaculate. Everything is perfect. That\'s the problem — the last investigator sent the same report before he vanished.', title: 'Too Perfect', origins: ['church-raised'], classes: ['Inquisitor'], frame: { objective: 'Find what the monastery is hiding', crucible: 'Perfect cooperation from people who made the last investigator disappear' }, arc: { name: 'Too Perfect', episode: 'Observe the monastery routines and identify the first crack in the performance' } },
    { hook: 'A condemned man, hours from execution, demands to speak to an inquisitor. Not a priest — an inquisitor. He says his confession will implicate three sitting members of the council. The council says he\'s lying to delay the rope. He says he can prove it, but only to someone with the authority to act.', title: 'The Last Confession', origins: ['church-raised'], classes: ['Inquisitor'], frame: { objective: 'Hear the confession and judge its truth before the execution', crucible: 'Hours until the rope, a claim against the council, and no time to verify before deciding' }, arc: { name: 'The Last Confession', episode: 'Interrogate the condemned man and assess whether his evidence is real' } },
    { hook: 'A Church-run orphanage in the Wasting zone has been turning away children. The official reason: overcrowding. The unofficial reason reaches you through a Shepherd who can\'t sleep: the Church is triaging. Children from families that tithed are admitted. Children from families that didn\'t are sent back to die. The Shepherd asks whether this is doctrine or murder, and whether there\'s a difference. The bishop who issued the policy is arriving tomorrow to inspect the orphanage. He\'s a good man. He made this decision because the alternative was losing the orphanage entirely.', title: 'The Triage', origins: ['church-raised'], classes: ['Shepherd', 'Inquisitor'], frame: { objective: 'Decide what to do before the bishop arrives', crucible: 'Children sorted by their parents\' faith, a Shepherd who can\'t bear it, and a bishop whose decision was defensible and devastating' }, arc: { name: 'The Triage', episode: 'Visit the orphanage, meet the children who were turned away, and prepare for the bishop\'s arrival' } },
  ],
  initialChapterTitle: 'First Blood',
  locationNames: [
    'The Ashfang Company', 'The Iron Pact', 'The Pale March',
    'The Thorn Company', 'The Last Warrant', 'The Grey Vanguard',
    'The Ember Compact', 'The Broken Seal', 'The Hollow Banner', 'The Black Vigil',
  ],
  npcNames: [
    'Harven', 'Breck', 'Oswick', 'Dalla', 'Fenmark', 'Greth', 'Ulra', 'Morwen',
    'Tove', 'Aldwin', 'Sigra', 'Kord', 'Wulfric', 'Etta', 'Haldren', 'Maren',
    'Brant', 'Helga', 'Torsten', 'Gerta', 'Rickard', 'Edda', 'Osmund', 'Vitta',
    'Gorath', 'Brita', 'Leofric', 'Thyra', 'Caskwell', 'Anneke', 'Dunstan',
    'Ragna', 'Blaeric', 'Hildeth', 'Yoren',
  ],
}


export default grimdarkConfig
